<?php

// i18n - Russian Language Pack (System Messages)
return array(
    'Available interfaces: {availableInterfaces}.' => 'Доступные внешние виды: {availableInterfaces}.', /*'Р”РѕСЃС‚СѓРїРЅС‹Рµ РІРЅРµС€РЅРёРµ РІРёРґС‹: {availableInterfaces}.'*/
    'Available languages: {availableLanguages}.' => 'Доступные языки: {availableLanguages}.', /*'Р”РѕСЃС‚СѓРїРЅС‹Рµ СЏР·С‹РєРё: {availableLanguages}.'*/
    'Could not load {model} model. Model ID: {modelId}. Method called: {method}.' => 'Не удалось загрузить модель {model}. Модель ID: {modelId}. Вызывался метод: {method}.', /*'РќРµ СѓРґР°Р»РѕСЃСЊ Р·Р°РіСЂСѓР·РёС‚СЊ РјРѕРґРµР»СЊ {model}. РњРѕРґРµР»СЊ ID: {modelId}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Could not save attributes of the {model} model. Model ID: {modelId}. Method called: {method}.' => 'Не смог сохранить атрибуты модели {model}. Модель ID: {modelId}. Вызывался метод: {method}.', /*'РќРµ СЃРјРѕРі СЃРѕС…СЂР°РЅРёС‚СЊ Р°С‚СЂРёР±СѓС‚С‹ РјРѕРґРµР»Рё {model}. РњРѕРґРµР»СЊ ID: {modelId}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Failed creating UserDetails record. Member ID: {userId}. Method called: {method}.' => 'Не удалось создать запись UserDetails. ID участника: {userId}. Вызывался метод: {method}.', /*'РќРµ СѓРґР°Р»РѕСЃСЊ СЃРѕР·РґР°С‚СЊ Р·Р°РїРёСЃСЊ UserDetails. ID СѓС‡Р°СЃС‚РЅРёРєР°: {userId}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Incorrect parameter in method call: {method}.' => 'Неверный параметер в вызове метода: {method}.', /*'РќРµРІРµСЂРЅС‹Р№ РїР°СЂР°РјРµС‚РµСЂ РІ РІС‹Р·РѕРІРµ РјРµС‚РѕРґР°: {method}.'*/
    'Member with ID {userId} has no UserDetails record associated. Method called: {method}.' => 'Участник с ID {userId} не имеет соответствующей UserDetails записи. Вызывался метод: {method}.', /*'РЈС‡Р°СЃС‚РЅРёРє СЃ ID {userId} РЅРµ РёРјРµРµС‚ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓСЋС‰РµР№ UserDetails Р·Р°РїРёСЃРё. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Missing parameter in file params.php: {parameter}.' => 'Пропущен параметр в файле params.php: {parameter}.', /*РџСЂРѕРїСѓС‰РµРЅ РїР°СЂР°РјРµС‚СЂ РІ С„Р°Р№Р»Рµ params.php: {parameter}.'*/
    'Unacceptable value of {parameter} system parameter: {value}. Method called: {method}.' => 'Недопустимое значение {parameter} системного параметра: {value}. Вызывался метод: {method}.', /*'РќРµРґРѕРїСѓСЃС‚РёРјРѕРµ Р·РЅР°С‡РµРЅРёРµ {parameter} СЃРёСЃС‚РµРјРЅРѕРіРѕ РїР°СЂР°РјРµС‚СЂР°: {value}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Unacceptable values of layout constants... content: {content}, sidebar1: {sidebar1}, sidebar2: {sidebar2}, total: {total}. Method called: {method}.' => 'Недопустимые значения констант расположения... содержание: {content}, колонка1: {sidebar1}, колонка2: {sidebar2}, всего: {total}. Вызывался метод: {method}.', /*'РќРµРґРѕРїСѓСЃС‚РёРјС‹Рµ Р·РЅР°С‡РµРЅРёСЏ РєРѕРЅСЃС‚Р°РЅС‚ СЂР°СЃРїРѕР»РѕР¶РµРЅРёСЏ... СЃРѕРґРµСЂР¶Р°РЅРёРµ: {content}, РєРѕР»РѕРЅРєР°1: {sidebar1}, РєРѕР»РѕРЅРєР°2: {sidebar2}, РІСЃРµРіРѕ: {total}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Unacceptable values of layout parameters... content: {content}, sidebar1: {sidebar1}, sidebar2: {sidebar2}, total: {total}. Method called: {method}.' => 'Недопустимые значения параметров расположения... содержание: {content}, колонка1: {sidebar1}, колонка2: {sidebar2}, всего: {total}. Вызывался метод: {method}.', /*'РќРµРґРѕРїСѓСЃС‚РёРјС‹Рµ Р·РЅР°С‡РµРЅРёСЏ РїР°СЂР°РјРµС‚СЂРѕРІ СЂР°СЃРїРѕР»РѕР¶РµРЅРёСЏ... СЃРѕРґРµСЂР¶Р°РЅРёРµ: {content}, РєРѕР»РѕРЅРєР°1: {sidebar1}, РєРѕР»РѕРЅРєР°2: {sidebar2}, РІСЃРµРіРѕ: {total}. Р’С‹Р·С‹РІР°Р»СЃСЏ РјРµС‚РѕРґ: {method}.'*/
    'Uncommon parameter in method call: {method}.' => 'Необычный параметер в вызове метода: {method}.', /*'РќРµРѕР±С‹С‡РЅС‹Р№ РїР°СЂР°РјРµС‚РµСЂ РІ РІС‹Р·РѕРІРµ РјРµС‚РѕРґР°: {method}.'*/
);
