<?php

// i18n - Russian Language Pack (User Messages)
return array(
    'A member account with email address {email} could not be found.' => 'РЈС‡С‘С‚РЅР°СЏ Р·Р°РїРёСЃСЊ СЃ РµРјР°Р№Р» Р°РґСЂРµСЃРѕРј {email} РЅРµ РјРѕРіР»Р° Р±С‹С‚СЊ РЅР°Р№РґРµРЅР°.', /*'Учётная запись с емайл адресом {email} не могла быть найдена.'*/
    'Create a new member account. It\'s free and easy!' => 'РЎРѕР·РґР°С‚СЊ РЅРѕРІСѓСЋ СѓС‡С‘С‚РЅСѓСЋ Р·Р°РїРёСЃСЊ. Р­С‚Рѕ Р»РµРіРєРѕ Рё Р±РµСЃРїР»Р°С‚РЅРѕ!', /*'Создать новую учётную запись. Это легко и бесплатно!'*/
    'Email address {email} has been successfully confirmed.' => 'Р•РјР°Р№Р» Р°РґСЂРµСЃ {email} Р±С‹Р» СѓСЃРїРµС€РЅРѕ РїРѕРґС‚РІРµСЂР¶РґС‘РЅ.', /*'Емайл адрес {email} был успешно подтверждён.'*/
    'Email address {email} was confirmed earlier.' => 'Р•РјР°Р№Р» Р°РґСЂРµСЃ {email} Р±С‹Р» РїРѕРґС‚РІРµСЂР¶РґС‘РЅ СЂР°РЅРµРµ.', /*'Емайл адрес {email} был подтверждён ранее.'*/
    'Error! Email address {email} could not be confirmed.' => 'РћС€РёР±РєР°! Р•РјР°Р№Р» Р°РґСЂРµСЃ {email} РЅРµ РјРѕРі Р±С‹С‚СЊ РїРѕРґС‚РІРµСЂР¶РґС‘РЅ.', /*'Ошибка! Емайл адрес {email} не мог быть подтверждён.'*/
    'Error! {screenName}, new user interface could not be applied.' => 'РћС€РёР±РєР°! {screenName}, РЅРѕРІС‹Р№ РІРЅРµС€РЅРёР№ РІРёРґ РЅРµ РјРѕРі Р±С‹С‚СЊ РїСЂРёРјРµРЅС‘РЅ.', /*'Ошибка! {screenName}, новый внешний вид не мог быть применён.'*/
    'Error! {screenName}, your profile could not be updated.' => 'РћС€РёР±РєР°! {screenName}, РІР°С€ РїСЂРѕС„РёР»СЊ РЅРµ РјРѕРі Р±С‹С‚СЊ РѕР±РЅРѕРІР»С‘РЅ.', /*'Ошибка! {screenName}, ваш профиль не мог быть обновлён.'*/
    'If you have business inquiries or other questions, please fill out this form to contact us. Thank you.' => 'Р•СЃР»Рё Сѓ РІР°СЃ РµСЃС‚СЊ Р±РёР·РЅРµСЃ Р·Р°РїСЂРѕСЃС‹ РёР»Рё РґСЂСѓРіРёРµ РІРѕРїСЂРѕСЃС‹, РїРѕР¶Р°Р»СѓР№СЃС‚Р° Р·Р°РїРѕР»РЅРёС‚Рµ СЌС‚Сѓ С„РѕСЂРјСѓ С‡С‚РѕР±С‹ СЃРІСЏР·Р°С‚СЊСЃСЏ СЃ РЅР°РјРё. РЎРїР°СЃРёР±Рѕ.', /*'Если у вас есть бизнес запросы или другие вопросы, пожалуйста заполните эту форму чтобы связаться с нами. Спасибо.'*/
    'Letters are not case-sensitive.' => 'Р‘СѓРєРІС‹ СЏРІР»СЏСЋС‚СЃСЏ СЂРµРіРёСЃС‚СЂРѕ-РЅРµР·Р°РІРёСЃРёРјС‹РјРё.', /*'Буквы являются регистро-независимыми'*/
    'Please enter the letters as they are shown in the image above.' => 'РџРѕР¶Р°Р»СѓР№СЃС‚Р° РІРІРµРґРёС‚Рµ Р±СѓРєРІС‹ РєР°Рє РѕРЅРё РїРѕРєР°Р·Р°РЅС‹ РЅР° СЂРёСЃСѓРЅРєРµ СЃРІРµСЂС…Сѓ.', /*'Пожалуйста введите буквы как они показаны на рисунке сверху'*/
    'Please fix the following input errors:' => 'РџРѕР¶Р°Р»СѓР№СЃС‚Р° РёСЃРїСЂР°РІСЊС‚Рµ СЃР»РµРґСѓСЋС‰РёРµ РѕС€РёР±РєРё РІРІРѕРґР°:', /*'Пожалуйста исправьте следующие ошибки ввода:'*/
    '{screenName}, new user interface has been applied.' => '{screenName}, РЅРѕРІС‹Р№ РІРЅРµС€РЅРёР№ РІРёРґ Р±С‹Р» СѓСЃРїРµС€РЅРѕ РїСЂРёРјРµРЅС‘РЅ.', /*'{screenName}, новый внешний вид был успешно применён.'*/
    '{screenName}, this action will log you out from your current account.' => '{screenName}, РґР°РЅРЅС‹Рј РґРµР№СЃС‚РІРёРµРј РІС‹ РїРѕРєРёРЅРµС‚Рµ РІР°С€Сѓ С‚РµРєСѓС‰СѓСЋ СѓС‡РµС‚РЅСѓСЋ Р·Р°РїРёСЃСЊ.', /*'{screenName}, данным действием вы покинете вашу текущую учетную запись.'*/
    '{screenName}, welcome back! Automatic authentication has been successfully passed.' => '{screenName}, РґРѕР±СЂРѕ РїРѕР¶Р°Р»РѕРІР°С‚СЊ РЅР°Р·Р°Рґ! РђРІС‚РѕРјР°С‚РёС‡РµСЃРєР°СЏ РїСЂРѕРІРµСЂРєР° РїРѕРґР»РёРЅРЅРѕСЃС‚Рё Р±С‹Р»Р° СѓСЃРїРµС€РЅРѕ РІС‹РїРѕР»РЅРµРЅР°.', /*'{screenName}, добро пожаловать назад! Автоматическая проверка подлинности была успешно выполнена.'*/
    '{screenName}, you have been successfully logged in.' => '{screenName}, РІС‹ СѓСЃРїРµС€РЅРѕ РІРѕС€Р»Рё РІ СЃРёСЃС‚РµРјСѓ.', /*'{screenName}, вы успешно вошли в систему.'*/
    '{screenName}, you have been successfully logged out.' => '{screenName}, РІС‹ СѓСЃРїРµС€РЅРѕ РІС‹С€Р»Рё РёР· СЃРёСЃС‚РµРјС‹.', /*'{screenName}, вы успешно вышли из системы.'*/
    '{screenName}, your member account has been successfully created.' => '{screenName}, РІР°С€Р° СѓС‡С‘С‚РЅР°СЏ Р·Р°РїРёСЃСЊ Р±С‹Р»Р° СѓСЃРїРµС€РЅРѕ СЃРѕР·РґР°РЅР°.', /*'{screenName}, ваша учётная запись была успешно создана.'*/
    '{screenName}, your profile has been updated.' => '{screenName}, РІР°С€ РїСЂРѕС„РёР»СЊ Р±С‹Р» РѕР±РЅРѕРІР»С‘РЅ.', /*'{screenName}, ваш профиль был обновлён.'*/
    'System failure! Please accept our apologies...' => 'РЎРёСЃС‚РµРјРЅР°СЏ РѕС€РёР±РєР°! РџСЂРёРЅРѕСЃРёРј РЅР°С€Рё РёР·РІРёРЅРµРЅРёСЏ...', /*'Системная ошибка! Приносим наши извинения...'*/
    'Thank you for contacting us. We will respond to you as soon as possible.' => '<strong>РЎРїР°СЃРёР±Рѕ</strong> С‡С‚Рѕ СЃРІСЏР·Р°Р»РёСЃСЊ СЃ РЅР°РјРё. РњС‹ РѕС‚РІРµС‚РёРј РІР°Рј РєР°Рє С‚РѕР»СЊРєРѕ Р±СѓРґРµС‚ РІРѕР·РјРѕР¶РЅРѕ.', /*'<strong>Спасибо</strong> что связались с нами. Мы ответим вам как только будет возможно.'*/
    'We are sorry, but email address {email} has a different confirmation key. You provided: {emailConfirmationKey}.' => 'РЎРѕР¶Р°Р»РµРµРј, РЅРѕ РµРјР°Р№Р» Р°РґСЂРµСЃСѓ {email} СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓРµС‚ РґСЂСѓРіРѕР№ РєР»СЋС‡ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ. Р’С‹ РїСЂРµРґРѕСЃС‚Р°РІРёР»Рё: {emailConfirmationKey}.', /*'Сожалеем, но емайл адресу {email} соответствует другой ключ подтверждения. Вы предоставили: {emailConfirmationKey}.'*/
    'We are sorry, but your access type is {accessType}. Required access type: {requiredAccessType}.' => 'РЎРѕР¶Р°Р»РµРµРј, РЅРѕ РІР°С€ С‚РёРї РґРѕСЃС‚СѓРїР° - {accessType}. РќРµРѕР±С…РѕРґРёРјС‹Р№ С‚РёРї РґРѕСЃС‚СѓРїР°: {requiredAccessType}.', /*'Сожалеем, но ваш тип доступа - {accessType}. Необходимый тип доступа: {requiredAccessType}.'*/
    'We are sorry, but your member account is marked as "inactive". Inactive member accounts are temporarely inaccessible. {contactLink}.' => 'РЎРѕР¶Р°Р»РµРµРј, РЅРѕ РІР°С€Р° СѓС‡С‘С‚РЅР°СЏ Р·Р°РїРёСЃСЊ РїРѕРјРµС‡РµРЅР° РєР°Рє "РЅРµР°РєС‚РёРІРЅР°СЏ". РќРµР°РєС‚РёРІРЅС‹Рµ СѓС‡РµС‚РЅС‹Рµ Р·Р°РїРёСЃРё РІСЂРµРјРµРЅРЅРѕ СЏРІР»СЏСЋС‚СЃСЏ РЅРµРґРѕСЃС‚СѓРїРЅС‹РјРё. {contactLink}.', /*'Сожалеем, но ваша учётная запись помечена как "неактивная". Неактивные учетные записи временно являются недоступными. {contactLink}.'*/
);
